### PR TITLE
fix stopping and removing animclip when deleting them

### LINKED ISSUE #577: Error while deleting an AnimClip
If you `delete` an animation that is currently playing, the character continues to move with the deleted animation and the animation tree breaks oddly showing empty icons at the removed animation.

Perhaps the correct order of operations should be:
```java
                if (animComposer.getCurrentAction() == animComposer.getAction(clipName)) {
                    animComposer.reset();
                }
                AnimClip clip = animComposer.getAnimClip(clipName);
                animComposer.removeAction(clipName);
                animComposer.removeAnimClip(clip);
                refreshAnimTree();
```

image

image

### PR DESCRIPTION
**Pull request by neph1**
Fixes #577

### CODE REVIEW

File: jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClip.java [hunk 1]
```diff
@@ -162,19 +163,20 @@ public void stop() {
...
-            lookupContents.remove(this.animClip);
-            lookupContents.remove(this);
-            SceneApplication.getApplication().enqueue(() -> {
-                control.removeAnimClip(this.animClip);
-                return null;
-            }).get();
-            setChanged();
-        } catch (InterruptedException | ExecutionException ex) {
-            Exceptions.printStackTrace(ex);
+        if (playing) {
```
Comment (neph1) [inline jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClip.java:168]: This stops the animation if it's playing

File: jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClip.java [hunk 2]
```diff
@@ -162,19 +163,20 @@ public void stop() {
...
+            control.removeCurrentAction(AnimComposer.DEFAULT_LAYER);
+            jmeControl.setAnimClip(null);
+            
         }
+        lookupContents.remove(JmeAnimClip.this.animClip);
+        lookupContents.remove(this);
+        SceneApplication.getApplication().enqueue( () -> {
+            control.removeAnimClip(this.animClip);
+            SwingUtilities.invokeLater(() -> jmeControl.refresh(false));
```
Comment (neph1) [inline jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimClip.java:177]: Need to refresh after the anim has been removed from the control

File: jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimComposer.java [hunk 3]
```diff
@@ -149,4 +149,10 @@ public Node[] createNodes(Object key, DataObject key2, boolean cookie) {
         JmeAnimClipChildren children = new JmeAnimClipChildren(this);
         return new Node[]{ new JmeAnimComposer((AnimComposer)key, children, key2)};
     }
+    
+    @Override
+    public void refresh(boolean immediate) {
+        ((JmeAnimClipChildren) jmeChildren).refreshChildren(immediate);
```
Comment (neph1) [inline jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/animation/JmeAnimComposer.java:155]: Refresh only happens if they are JmeSpatialChildren per default :shrug:

**Review by tonihele — APPROVED** [review]
