### PR TITLE
ExternalChangeScanner bug fixes and improvement

### LINKED ISSUE #343: "Remember this option" feature when applying changes
I think it would be neat if you got the option to always apply the same option after getting the initial "external change" dialog. If you for example choose "animations only", it will remember that for the rest of the session instead of showing the dialog every time. It would make for a smoother editing experience. It would be really simple to apply it in ExternalChangeScanner. The tricky part is the GUI, getting a checkbox(?) into the options dialog, or making a custom one.

### PR DESCRIPTION
**Pull request by neph1**
New feature:
Remember this option for ExternalChangeScanner. Fixes #343 
Bug fixes:
Exception for not executing on awt thread
Handling closing window without selecting an option
Screenshot from 2022-12-27 15-53-48

### CODE REVIEW

File: jme3-core/src/com/jme3/gde/core/assets/ExternalChangeScanner.java [hunk 1]
```diff
@@ -173,12 +208,16 @@ private void applyExternalData(final boolean onlyMeshData,
                 new CopyMaterialDataFromOriginal(finder).update(spat, original);
             }
             // Do a complicated recurse refresh since AbstractSceneExplorerNode:refresh() isn't working
-            SceneApplication.getApplication().enqueue((Runnable) () -> {
+            SwingUtilities.invokeLater(() -> {
```
Comment (neph1) [inline jme3-core/src/com/jme3/gde/core/assets/ExternalChangeScanner.java:211]: This solves an exception I don't remember seeing before

File: jme3-core/src/com/jme3/gde/core/assets/ExternalChangeScanner.java [hunk 2]
```diff
@@ -115,24 +129,34 @@ public void fileDeleted(FileEvent fe) {
...
+                
                 DialogDisplayer.getDefault().notify(message);
-                if (message.getValue().equals(noOption)) {
+
+                if(rememberSelectionBox.isSelected() && !message.getValue().equals(cancel)) {
+                    savedOption = message.getValue();
+                    LOGGER.log(Level.INFO, "Saving selection "
+                    + "{0}", savedOption);
+                }
+                if (message.getValue().equals(cancel) || message.getValue().equals(noOption)) {
```
Comment (neph1) [inline jme3-core/src/com/jme3/gde/core/assets/ExternalChangeScanner.java:159]: Previously didn't handle pressing the "x" to close the window.

**Comment by neph1** [comment]
Let me know if anyone wants to test this, or I'll merge it "soon"
